services:
  - type: web
    name: tokyo-experiences-dashboard
    runtime: docker
    plan: free
    envVars:
      - key: AIRTABLE_PAT
        sync: false
      - key: AIRTABLE_BASE_ID
        value: appBn4rAsuq14VeDf
      - key: AIRTABLE_TABLE_ID
        value: tblKlMT96Z03jLl1J
      - key: PORT
        value: 3456
